### PR TITLE
fix: desktop aiming

### LINKED ISSUE #3: Aiming is broken on desktop
A recent change made it so aiming on desktop is no longer possible.

micro-old

### PR DESCRIPTION
**Pull request by dewbjorn**
Hi there!

This fixes #3.

I noticed that after adding support for mobile devices, mouse aiming stopped working on desktop machines.

After looking into the code a bit, I noticed that the current code checks for mobile devices using the resolution. Even though this is unreliable (resolution alone is not enough), the new logic in the resulting index.html file also only took mobile devices into consideration and mistakenly ignored desktops.

So I basically changed it so the useragent gets checked, and the scale changes dynamically, leaving your initial `scale` calculation untouched.

You can see the fixed result in my [GitHub page](https://dewbjorn.github.io/micro-survivors/) for the project, and compare it with the existing one.

On a side note: thanks for making this game, I got addicted. :)

### CODE REVIEW

**Comment by SkaceKamen** [comment]
Hey, thanks for the change! Seems like you've forgot to attach the `main.js`?

**Comment by dewbjorn** [comment]
main.js wasn't changed, only the index files

**Comment by dewbjorn** [comment]
Oh, I see that I also pushed main.min.js. My bad there, on it

**Comment by dewbjorn** [comment]
main.min.js was there because I played around with main.js earlier. Eventually, it contains no changes. 

Pushed another change to exclude main.min.js. You can see the result here - https://dewbjorn.github.io/micro-survivors/

**Comment by dewbjorn** [comment]
Also works on mobile as intended :)

**Comment by SkaceKamen** [comment]
Thanks for the contribution! Anyway, I think the issue is actually at `main.js` where I initialize scale to `0`:
https://github.com/SkaceKamen/micro-survivors/blob/main/main.js#L47

It should be initialized to `1` and that should resolve the desktop issues without any changes to the HTML initialization. Your change actually fixed the issue because you also had default `1` scale, but I think matching the user agent is kind of unnecessary.

**Comment by dewbjorn** [comment]
That's a good call, and it indeed works.

I would however keep a better mobile check, since using resolution alone is unreliable afaik. Up to you 🤘🏻 

Anyway, scale is now 1 by default

**Review by SkaceKamen — APPROVED** [review]
Looks good, thanks for fixing this issue!

**Pull request merged**
